# Generated by Django 4.1.1 on 2022-09-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.IntegerField(verbose_name=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(verbose_name=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='contact_number',
            field=models.IntegerField(verbose_name=20),
        ),
    ]
