# Generated by Django 4.1.1 on 2022-09-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_customer_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
