# Generated by Django 4.1.1 on 2022-09-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_loggedinuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
